config/routes.rb
MyApp::Application.routes.draw do
  root :to =>'static_pages#home'
  
  match '/signup',   to: 'users#new'
  
  match '/help',     to: 'static_pages#help'
  match '/about',    to: 'static_pages#about'
  match '/contact',  to: 'static_pages#contact'

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email
  
  before_save { |user | user.email = user.email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[\w+\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'My App'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<a href="http://sameheaven.herokuapp.com">This on Heroku</a>
 by Iggy
</small>
<nav>
	<ul>
		<li><%= link_to "About",    about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
	</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
		<header class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
				<%= link_to "my app", root_path, id: "logo"%>
				<nav
				<ul class="nav pull-right">
					<li><%= link_to "Home",    root_path %></li>
					<li><%= link_to "Help",    help_path %></li>
					<li><%= link_to "Sign in", '#' %></li>
				</ul>
				</nav>
				</div>
			</div>
		</header>
		

app/views/layouts/_shim.html.erb
		<!--[if lt IE 9]>
		<script src="http:html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title> <%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim'%>
	</head>
	<body>
	<%= render 'layouts/header'%>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer'%>
		</div>
	</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About')%>
<h1>About us</h1>
<p>About</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>Contact</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help page</h1>
<p>Help</p>

app/views/static_pages/home.html.erb
<div class ="center hero-unit">
<h1>Welcome</h1>
<p>This page is created by following rubyonrails tutorial</p>
<%= link_to "Sign up", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'%>

app/views/users/new.html.erb
<% provide(:title, 'Sign up')%>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>